version: '3.8'

services:
  # Contenedor de la Base de Datos
  db:
    build: ./db                      # Usa db/Dockerfile para ejecutar init.sql
    container_name: tienda-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
    volumes:
      - dbdata:/var/lib/mysql        # PERSISTENCIA: los datos se guardan en el volumen 'dbdata'
    ports:
      - "3306:3306"
    healthcheck:                     # Espera a que MySQL acepte conexiones
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin123"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Contenedor del Backend
  backend:
    build: ./backend
    container_name: tienda-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
    depends_on:
      db:
        condition: service_healthy   # Arranca solo cuando la BD esté lista

  # Contenedor del Frontend (Nginx)
  frontend:
    build: ./frontend
    container_name: tienda-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# Definición del volumen para que Docker lo cree
volumes:
  dbdata:
